<a href="https://colab.research.google.com/github/Iftikhar-Shams-Niloy/TensorFlow-Cookbook/blob/main/1_Fundamentals_of_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This notebook covers the following:

1.  Tensors Introduction
2.  Information from Tensors
3.  Tensors Manipulation
4.  Tensors & NumPy
5.  Using @tf.function (Speeding up regular python functions)
6.  Using GPUs with TensorFlow (or TPUs)
7.  Exercises on the topics above.



# Tensors Introduction

## Import TensorFlow

In [ ]:
import tensorflow as tf
import tensorflow_probability as tfp
print(tf.__version__)

2.18.0


## Create Tensor with ```tf.constant()```



In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

## Checking the number of dimensions

In [ ]:
print(scalar.ndim)

0


## Create a vector

In [ ]:
my_vector = tf.constant([10, 11, 12])
print(my_vector)
print(my_vector.ndim)

tf.Tensor([10 11 12], shape=(3,), dtype=int32)
1


## Create multi-dimensional matrix

In [ ]:
my_matrix = tf.constant([[10, 11, 12],
                        [21, 22, 23],
                        [31, 32, 33]])
print(my_matrix)
print("MATRIX DIMENTIONS:",my_matrix.ndim)

tf.Tensor(
[[10 11 12]
 [21 22 23]
 [31 32 33]], shape=(3, 3), dtype=int32)
MATRIX DIMENTIONS: 2


In [ ]:
my_matrix2 = tf.constant([[10, 11, 12],
                        [21, 22, 23],
                        [31, 32, 33]], dtype=tf.float16)
print(my_matrix2)

tf.Tensor(
[[10. 11. 12.]
 [21. 22. 23.]
 [31. 32. 33.]], shape=(3, 3), dtype=float16)


In [ ]:
my_matrix3 = tf.constant([[[1,2,3],
                           [4,5,6]],

                           [[11, 22, 33],
                           [44,55,66]],

                           [[111,222,333],
                          [444,555,666]]])
print(my_matrix3)
print("MATRIX DIMENTIONS:",my_matrix3.ndim)

tf.Tensor(
[[[  1   2   3]
  [  4   5   6]]

 [[ 11  22  33]
  [ 44  55  66]]

 [[111 222 333]
  [444 555 666]]], shape=(3, 2, 3), dtype=int32)
MATRIX DIMENTIONS: 3


## Creating tensors using ```tf.Variable()```

In [ ]:
variable_tensor = tf.Variable([1,2,3])
constant_tensor = tf.constant([4,5,6])
print("Variable tensor:", variable_tensor)
print("Constant tensor:", constant_tensor)

Variable tensor: <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
Constant tensor: tf.Tensor([4 5 6], shape=(3,), dtype=int32)


We can change the variable_tensor like a 'list' but using specific function. However, we cannot change constant_tensor after making one.

In [ ]:
variable_tensor[0].assign(10)
print(variable_tensor.value())

tf.Tensor([10  2  3], shape=(3,), dtype=int32)


## Creating randor tensors using ```tf.random```

In [ ]:
my_random = tf.random.Generator.from_seed(42)
my_random = my_random.normal(shape=(3,2))
print(my_random)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


## Shuffling orders in Tensor

In [ ]:
my_random_shuffle = tf.random.shuffle(my_random)
print(my_random_shuffle)

tf.Tensor(
[[-0.23193763 -1.8107855 ]
 [ 0.07595026 -1.2573844 ]
 [-0.7565803  -0.06854702]], shape=(3, 2), dtype=float32)


If we want to shuffle tensor in the same order each time (use seeding), we need to set the global seeding as well as seeding inside the shuffle() function to achieve what we are trying to achieve. An example is given below:

In [ ]:
tf.random.set_seed(42)
my_random_shuffle2 = tf.random.shuffle(my_random, seed=42)
print(my_random_shuffle2)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


## Creating zeros and ones tensors

In [ ]:
my_zeros = tf.zeros(shape=(3,3))
print(my_zeros)

my_ones = tf.ones(shape=(3,3))
print(my_ones)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


## Converting Numpy arrays into Tensors

In [ ]:
import numpy as np
numpy_arr = np.arange(1,25, dtype=np.int32)
print(numpy_arr)

print("\n### Printing np_tensor1: ###")
np_tensor1 = tf.constant(numpy_arr)
print(np_tensor1)

print("\n### Printing np_tensor2: ###")
np_tensor2 = tf.constant(numpy_arr, shape=(2,3,4))
print(np_tensor2)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

### Printing np_tensor1: ###
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)

### Printing np_tensor2: ###
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


# Information from Tensors

### **Shape** (``` tensor.shape ```): Shape represents the length of each dimensions of a tensor.

### **Ranks** (``` tensor.ndim ```):
*  Scalar is rank 0
*  Vector is rank 1
*  Matrix is rank 2
*  Tensor is rank n

### **Axis or dimension** (```tensor[0], tensor[:,1]```): A particular dimension of a tensor

### **Size** (```tf.size(tensor)```): This function will show the total number of items in the tensor.



In [ ]:
tensor_rank4 = tf.zeros(shape=(2,3,4,5))
print(tensor_rank4)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [ ]:
print(" Datatype of every element:", tensor_rank4.dtype)
print(" Number of dimensions (rank):", tensor_rank4.ndim)
print(" Shape of tensor:", tensor_rank4.shape)
print(" Elements along axis 0 of tensor:", tensor_rank4.shape[0])
print(" Elements along last axis of tensor:", tensor_rank4.shape[-1])
print(" Total number of elements in our tensor:", tf.size(tensor_rank4))
print(" Total number of elements in our tensor:", tf.size(tensor_rank4).numpy())

 Datatype of every element: <dtype: 'float32'>
 Number of dimensions (rank): 4
 Shape of tensor: (2, 3, 4, 5)
 Elements along axis 0 of tensor: 2
 Elements along last axis of tensor: 5
 Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
 Total number of elements in our tensor: 120


## Indexing Tensors

In [ ]:
print(tensor_rank4[:2,:2,:2,:2])

tf.Tensor(
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]], shape=(2, 2, 2, 2), dtype=float32)


In [ ]:
tensor_rank2 = tf.constant([[1,2,3],
                            [4,5,6]])
print(tensor_rank2)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
print(tensor_rank2[:,-1])

tf.Tensor([3 6], shape=(2,), dtype=int32)


## Tensor Dimension Expansion

In [ ]:
tf.expand_dims(tensor_rank2, axis=-1)

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]], dtype=int32)>

In [ ]:
tf.expand_dims(tensor_rank2, axis=0)

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

# Tensor Manipulation

### Basic Operations (```+ - * /```)

In [ ]:
my_tensor = tf.constant([[1,2,3],
                         [4,5,6],
                         [7,8,9]])
print(my_tensor + 10)
print(my_tensor * 10)
print(my_tensor / 10)
print(my_tensor - 10)

tf.Tensor(
[[11 12 13]
 [14 15 16]
 [17 18 19]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[10 20 30]
 [40 50 60]
 [70 80 90]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]], shape=(3, 3), dtype=int32)


### Using tf.multiply for multiplication

In [ ]:
print(my_tensor*10)
print(tf.multiply(my_tensor,10))

tf.Tensor(
[[10 20 30]
 [40 50 60]
 [70 80 90]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[10 20 30]
 [40 50 60]
 [70 80 90]], shape=(3, 3), dtype=int32)


### Matrix multipliation
We can do matrix multiplication using the following methods,<br>
➡️ ```tf.matmul(tensor1, tensor2)``` <br>
➡️ ```tensor1 @ tensor2```

In [ ]:
print(my_tensor)
print(tf.matmul(my_tensor, my_tensor)) # Method-1
print(my_tensor @ my_tensor) # Method-2

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]], shape=(3, 3), dtype=int32)


### Reshape and Transpose

In [ ]:
print(tf.reshape(my_tensor, shape=(1,9)))
print(tf.transpose(my_tensor))

tf.Tensor([[1 2 3 4 5 6 7 8 9]], shape=(1, 9), dtype=int32)
tf.Tensor(
[[1 4 7]
 [2 5 8]
 [3 6 9]], shape=(3, 3), dtype=int32)


### Dot Product of Matrices
➡️To perform the dot product we need to use ```tf.tensordot()```

In [ ]:
print(tf.tensordot(my_tensor, my_tensor, axes=1))
print("###########################################")
print(tf.tensordot(my_tensor, my_tensor, axes=0))

tf.Tensor(
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]], shape=(3, 3), dtype=int32)
###########################################
tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[ 2  4  6]
   [ 8 10 12]
   [14 16 18]]

  [[ 3  6  9]
   [12 15 18]
   [21 24 27]]]


 [[[ 4  8 12]
   [16 20 24]
   [28 32 36]]

  [[ 5 10 15]
   [20 25 30]
   [35 40 45]]

  [[ 6 12 18]
   [24 30 36]
   [42 48 54]]]


 [[[ 7 14 21]
   [28 35 42]
   [49 56 63]]

  [[ 8 16 24]
   [32 40 48]
   [56 64 72]]

  [[ 9 18 27]
   [36 45 54]
   [63 72 81]]]], shape=(3, 3, 3, 3), dtype=int32)


Let's assume we are working with two (3,2) tensors or matrices. As we cannot multiply these two because of their mismatched dimension we need to change their dimension either using Transpose or Reshape. In that case, it is better to transpose a tensor/matrix rather than reshaping it.

---

### Changing the datatype of tensor

In [ ]:
tensor_a = tf.constant([1,2,3,4,5])
tensor_b = tf.constant([1.1, 2.2, 3.3, 4.4])

print(tensor_a)
print(tensor_b)
print(tensor_a.dtype)
print(tensor_b.dtype)

tensor_a = tf.cast(tensor_a, dtype=tf.float16)
tensor_b = tf.cast(tensor_b, dtype=tf.int16)

print(tensor_a)
print(tensor_b)
print(tensor_a.dtype)
print(tensor_b.dtype)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([1.1 2.2 3.3 4.4], shape=(4,), dtype=float32)
<dtype: 'int32'>
<dtype: 'float32'>
tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float16)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int16)
<dtype: 'float16'>
<dtype: 'int16'>


### Tensors Aggregation
-> Condensing them from multiple values down to a smaller amount of values.

In [ ]:
tensor_c = tf.constant([1,-2,3])
print(tf.abs(tensor_c))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


### Getting Maximum Value

In [ ]:
tensor_d = tf.constant(np.random.randint(0,100, size=50))
print(tensor_d)
print("#################################################")
print(tf.reduce_max(tensor_d))

tf.Tensor(
[17 14 86 32 46 14 40 63 17 94 74 72 77 64 12 78 21  3 31 21 88 37 22 93
 91 30 16 68  2 93 63 94 58 40 96 24 91 65 52 24  9 21 94  1 87 84 38  2
  1 65], shape=(50,), dtype=int64)
#################################################
tf.Tensor(96, shape=(), dtype=int64)


### Getting Minimum Value

In [ ]:
tensor_d = tf.constant(np.random.randint(0,100, size=50))
print(tensor_d)
print("#################################################")
print(tf.reduce_min(tensor_d))

tf.Tensor(
[82 99 89 39 88 12  4 35 65 42 76 85 25 16 55 46 46  4 47 52  6 44 30  6
 80 81 53 10 77 58 97 12 86 88 80 15  6 82 42 42 85 20 68 74 51 50 43 22
 30 87], shape=(50,), dtype=int64)
#################################################
tf.Tensor(4, shape=(), dtype=int64)


### Getting Mean of a Tensor

In [ ]:
print(tf.reduce_mean(tensor_d))

tf.Tensor(50, shape=(), dtype=int64)


### Getting Sum of a Tensor

In [ ]:
tf.reduce_sum(tensor_d) # The numpy = __ is the sum!

<tf.Tensor: shape=(), dtype=int64, numpy=2532>

### Finding Variance of a Tensor

In [ ]:
tfp.stats.variance(tensor_d)

<tf.Tensor: shape=(), dtype=int64, numpy=845>

### Finding Standard Deviance of a Tensor

In [ ]:
tensor_d = tf.cast(tensor_d,dtype = tf.float32)
tf.math.reduce_std(tensor_d)

<tf.Tensor: shape=(), dtype=float32, numpy=29.064590454101562>

### Finding the postion/index of max and min

In [ ]:
tf.random.set_seed(42)
tensor_e = tf.random.uniform(shape=[50])
print(tensor_e)
print("#################################################")
print(tf.argmax(tensor_e))
print(tensor_e[tf.argmax(tensor_e)])
print("#################################################")
print(tf.argmin(tensor_e))
print(tensor_e[tf.argmin(tensor_e)])

tf.Tensor(
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
 0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
 0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
 0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
 0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
 0.9671384  0.06870162 0.79873943 0.66028714 0.5871513  0.16461694
 0.7381023  0.32054043], shape=(50,), dtype=float32)
#################################################
tf.Tensor(42, shape=(), dtype=int64)
tf.Tensor(0.9671384, shape=(), dtype=float32)
#################################################
tf.Tensor(16, shape=(), dtype=int64)
tf.Tensor(0.009463668, shape=(), dtype=float32)


### Removing all single dimensions in a Tensor

In [ ]:
tensor_f = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
print(tensor_f)
print("#############################")
print(tensor_f.shape)

tf.Tensor(
[[[[[0.68789124 0.48447883 0.9309944  0.252187   0.73115396 0.89256823
     0.94674826 0.7493341  0.34925628 0.54718256 0.26160395 0.69734323
     0.11962581 0.53484344 0.7148968  0.87501776 0.33967495 0.17377627
     0.4418521  0.9008261  0.13803864 0.12217975 0.5754491  0.9417181
     0.9186585  0.59708476 0.6109482  0.82086265 0.83269787 0.8915849
     0.01377225 0.49807465 0.57503664 0.6856195  0.75972784 0.908944
     0.40900218 0.8765154  0.53890026 0.42733097 0.401173   0.66623247
     0.16348064 0.18220246 0.97040176 0.06139731 0.53034747 0.9869994
     0.4746945  0.8646754 ]]]]], shape=(1, 1, 1, 1, 50), dtype=float32)
#############################
(1, 1, 1, 1, 50)


In [ ]:
squeezed_tensor_f = tf.squeeze(tensor_f)
print(squeezed_tensor_f)
print("#############################")
print(squeezed_tensor_f.shape)

tf.Tensor(
[0.68789124 0.48447883 0.9309944  0.252187   0.73115396 0.89256823
 0.94674826 0.7493341  0.34925628 0.54718256 0.26160395 0.69734323
 0.11962581 0.53484344 0.7148968  0.87501776 0.33967495 0.17377627
 0.4418521  0.9008261  0.13803864 0.12217975 0.5754491  0.9417181
 0.9186585  0.59708476 0.6109482  0.82086265 0.83269787 0.8915849
 0.01377225 0.49807465 0.57503664 0.6856195  0.75972784 0.908944
 0.40900218 0.8765154  0.53890026 0.42733097 0.401173   0.66623247
 0.16348064 0.18220246 0.97040176 0.06139731 0.53034747 0.9869994
 0.4746945  0.8646754 ], shape=(50,), dtype=float32)
#############################
(50,)


# One-hot Encoding

Simplest way to do on-hot encoding

In [ ]:
color_info = {'red':0, 'blue':1, 'green':2}
color_list = [0,1,2]
tensor_colors = tf.one_hot(color_list, depth=3)
print(tensor_colors)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


Custom "on value" and "off value" can be selected while doing one-hot encoding, following the method below.

In [ ]:
tensor_colors_2 = tf.one_hot(color_list, depth=3, on_value="Yes", off_value="No")
print(tensor_colors_2)

tf.Tensor(
[[b'Yes' b'No' b'No']
 [b'No' b'Yes' b'No']
 [b'No' b'No' b'Yes']], shape=(3, 3), dtype=string)


# Mathemetical Operations

In [ ]:
my_tensor2 = tf.range(1,11)
print(my_tensor2)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)


### Square Root
We need to convert the datatype into float32 before we do the square root of a tensor. Otherwise it will show an error

In [ ]:
my_tensor_root = tf.sqrt(tf.cast(my_tensor2, dtype=tf.float32))
print(my_tensor_root)

tf.Tensor(
[1.        1.4142135 1.7320508 2.        2.236068  2.4494898 2.6457512
 2.828427  3.        3.1622777], shape=(10,), dtype=float32)


### Log
We need to convert the datatype into float32 before we try to calculate the log of a tensor. Otherwise, it will show an error.

In [ ]:
my_tensor_log = tf.math.log(tf.cast(my_tensor2, dtype=tf.float32))
print(my_tensor_log)

tf.Tensor(
[0.        0.6931472 1.0986123 1.3862944 1.609438  1.7917595 1.9459102
 2.0794415 2.1972246 2.3025851], shape=(10,), dtype=float32)


# Tensors and Numpy

### Converting a numpy array into a tensor

In [ ]:
numpy_arr = np.arange(1,11,dtype=np.int32)
print(numpy_arr)
print(type(numpy_arr))

print("#################################")
np_to_tensor = tf.constant(numpy_arr)
print(np_to_tensor)
print(type(np_to_tensor))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
#################################
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


### Converting a tensor back into numpy array

In [ ]:
tensor_to_numpy = np.array(np_to_tensor)
print(tensor_to_numpy)
print(type(tensor_to_numpy))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


### Finding Access to GPU

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:TPU_SYSTEM:0', device_type='TPU_SYSTEM'),
 PhysicalDevice(name='/physical_device:TPU:0', device_type='TPU'),
 PhysicalDevice(name='/physical_device:TPU:1', device_type='TPU'),
 PhysicalDevice(name='/physical_device:TPU:2', device_type='TPU'),
 PhysicalDevice(name='/physical_device:TPU:3', device_type='TPU'),
 PhysicalDevice(name='/physical_device:TPU:4', device_type='TPU'),
 PhysicalDevice(name='/physical_device:TPU:5', device_type='TPU'),
 PhysicalDevice(name='/physical_device:TPU:6', device_type='TPU'),
 PhysicalDevice(name='/physical_device:TPU:7', device_type='TPU')]